version: '3'
services:
        databases:
                image: mysql
                ports:
                - "3306:3306"
                environment :
                - MYSQL_ROOT_PASSWORD=asghar

        web:
                image: nginx
                ports:
                - "1234:80"
