version: '3'
services:
        databases:
                image: redis
                ports:
                - "6379:6379"
        web:
                image: nginx
                ports:
                - "1234:80"
